# syntax=docker/dockerfile:1

#build docker
FROM node:24-alpine AS build

WORKDIR /src

COPY package*.json yarn.lock ./
#RUN yarn install



RUN corepack enable
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build


#prod docker
FROM nginx:stable-alpine AS final
COPY --from=build /src/dist /usr/share/nginx/html

EXPOSE 3001
CMD ["nginx", "-g", "daemon off;"]